import type { EnvVarDef, FeatureFlagDef, IntegrationDef, IntegrationProviderType } from '@/lib/integrations/types';

const sel = (...v: string[]) => v.map((x) => ({ value: x, label: x }));

export const INTEGRATIONS: IntegrationDef[] = [
  {
    id: 'notification',
    label: 'اعلان‌ها',
    description: 'سرویسِ مرکزیِ ارسالِ رویدادها (یادآوریِ چک‌این، هشدارِ مهلت، بازشدنِ اختلاف، آزادسازیِ جایزه، پاسخِ تیکت).',
    providers: sel('internal_mock', 'custom_api', 'firebase', 'one_signal', 'pusher_beams'),
    mockProvider: 'internal_mock',
    fields: [
      { key: 'baseUrl', label: 'Base URL', kind: 'text', placeholder: 'https://api.notify.example.com', required: true },
      { key: 'apiKey', label: 'API Key', kind: 'password', secret: true, required: true },
      { key: 'appId', label: 'App ID', kind: 'text' },
      { key: 'defaultChannel', label: 'کانالِ پیش‌فرض', kind: 'select', options: sel('in_app', 'email', 'sms', 'push'), defaultValue: 'in_app' },
      { key: 'retryCount', label: 'تعدادِ تلاشِ مجدد', kind: 'number', defaultValue: 3, advanced: true },
      { key: 'retryDelay', label: 'تأخیرِ تلاش (ثانیه)', kind: 'number', defaultValue: 30, advanced: true },
      { key: 'rateLimit', label: 'محدودیتِ نرخ (در دقیقه)', kind: 'number', defaultValue: 120, advanced: true },
      { key: 'deliveryLogs', label: 'ثبتِ لاگِ تحویل', kind: 'toggle', defaultValue: true, advanced: true },
    ],
    requiredEnvs: ['NOTIFICATION_PROVIDER', 'NOTIFICATION_API_KEY'],
    dependentFeatures: ['یادآوریِ چک‌این', 'هشدارِ نتیجه‌ی ثبت‌نشده', 'بازشدنِ اختلاف', 'آزادسازیِ جایزه', 'پاسخِ تیکت'],
    toggleListTitle: 'رویدادهای فعال',
    toggleList: [
      { key: 'tournament_registration_success', label: 'ثبت‌نامِ موفق' },
      { key: 'checkin_reminder', label: 'یادآوریِ چک‌این' },
      { key: 'checkin_expired', label: 'پایانِ مهلتِ چک‌این' },
      { key: 'match_deadline_warning', label: 'هشدارِ مهلتِ مسابقه' },
      { key: 'match_result_missing', label: 'نتیجه‌ی ثبت‌نشده' },
      { key: 'result_submitted', label: 'ثبتِ نتیجه' },
      { key: 'opponent_confirmation_required', label: 'نیازِ تأییدِ حریف' },
      { key: 'dispute_opened', label: 'بازشدنِ اختلاف' },
      { key: 'no_show_warning', label: 'هشدارِ عدمِ حضور' },
      { key: 'player_disqualified', label: 'محرومیتِ بازیکن' },
      { key: 'next_round_generated', label: 'ساختِ دورِ بعد' },
      { key: 'payout_released', label: 'آزادسازیِ جایزه' },
      { key: 'ticket_replied', label: 'پاسخِ تیکت' },
    ],
  },
  {
    id: 'email',
    label: 'ایمیل',
    description: 'ارسالِ ایمیل‌های تراکنشی و قالب‌ها (خوش‌آمد، تأییدِ ایمیل، بازنشانیِ رمز، رویدادهای تورنومنت).',
    providers: sel('internal_mock', 'smtp', 'resend', 'sendgrid', 'mailgun', 'ses'),
    mockProvider: 'internal_mock',
    fields: [
      { key: 'fromName', label: 'نامِ فرستنده', kind: 'text', placeholder: 'SHELTER', required: true },
      { key: 'fromEmail', label: 'ایمیلِ فرستنده', kind: 'text', placeholder: 'no-reply@shelter.gg', required: true },
      { key: 'replyTo', label: 'Reply-To', kind: 'text' },
      { key: 'apiKey', label: 'API Key', kind: 'password', secret: true },
      { key: 'smtpHost', label: 'SMTP Host', kind: 'text', advanced: true },
      { key: 'smtpPort', label: 'SMTP Port', kind: 'number', defaultValue: 587, advanced: true },
      { key: 'smtpUser', label: 'SMTP User', kind: 'text', advanced: true },
      { key: 'smtpPassword', label: 'SMTP Password', kind: 'password', secret: true, advanced: true },
      { key: 'secureTls', label: 'TLS امن', kind: 'toggle', defaultValue: true, advanced: true },
    ],
    requiredEnvs: ['EMAIL_PROVIDER', 'EMAIL_FROM', 'SMTP_HOST', 'SMTP_PORT', 'SMTP_USER', 'SMTP_PASSWORD'],
    dependentFeatures: ['تأییدِ ایمیل', 'بازنشانیِ رمز', 'یادآوری‌ها', 'گزارشِ نتایج'],
  },
  {
    id: 'sms',
    label: 'پیامک / OTP',
    description: 'ارسالِ پیامک و کدِ یک‌بارمصرف (تأییدِ شماره، 2FA، تأییدِ برداشتِ جایزه).',
    providers: sel('internal_mock', 'kavenegar', 'ghasedak', 'twilio', 'custom'),
    mockProvider: 'internal_mock',
    fields: [
      { key: 'apiKey', label: 'API Key', kind: 'password', secret: true, required: true },
      { key: 'sender', label: 'شماره‌ی فرستنده', kind: 'text', placeholder: '+98...' },
      { key: 'otpTemplate', label: 'شناسه‌ی قالبِ OTP', kind: 'text' },
      { key: 'countryCode', label: 'کدِ کشورِ پیش‌فرض', kind: 'text', defaultValue: '+98' },
      { key: 'otpLength', label: 'طولِ OTP', kind: 'number', defaultValue: 5, advanced: true },
      { key: 'otpExpiry', label: 'انقضای OTP (دقیقه)', kind: 'number', defaultValue: 2, advanced: true },
      { key: 'maxAttempts', label: 'حداکثرِ تلاش', kind: 'number', defaultValue: 5, advanced: true },
      { key: 'mockCode', label: 'کدِ آزمایشیِ توسعه', kind: 'text', defaultValue: '11111', advanced: true },
      { key: 'fallbackEmail', label: 'fallback به ایمیل', kind: 'toggle', defaultValue: true, advanced: true },
    ],
    requiredEnvs: ['SMS_PROVIDER', 'SMS_API_KEY'],
    dependentFeatures: ['تأییدِ شماره', '۲FA', 'تأییدِ برداشتِ جایزه', 'تأییدِ اقدامِ حساسِ مدیر'],
  },
  {
    id: 'chat',
    label: 'چتِ بلادرنگ',
    description: 'چتِ مسابقه، اعلانِ تورنومنت، پیامِ مستقیم و مانیتورینگِ مدیر.',
    providers: sel('internal_mock', 'websocket_server', 'supabase_realtime', 'pusher', 'socket_io', 'custom'),
    mockProvider: 'internal_mock',
    fields: [
      { key: 'wsUrl', label: 'WebSocket URL', kind: 'text', placeholder: 'wss://chat.shelter.gg', required: true },
      { key: 'authEndpoint', label: 'Auth Endpoint', kind: 'text' },
      { key: 'apiKey', label: 'API Key', kind: 'password', secret: true, required: true },
      { key: 'appId', label: 'App ID', kind: 'text' },
      { key: 'cluster', label: 'Cluster / Region', kind: 'text' },
      { key: 'retentionDays', label: 'نگه‌داریِ پیام (روز)', kind: 'number', defaultValue: 30, advanced: true },
      { key: 'maxLength', label: 'حداکثرِ طولِ پیام', kind: 'number', defaultValue: 500, advanced: true },
      { key: 'profanityFilter', label: 'فیلترِ ناسزا', kind: 'toggle', defaultValue: true, advanced: true },
      { key: 'attachments', label: 'پیوستِ فایل', kind: 'toggle', defaultValue: false, advanced: true },
      { key: 'readReceipts', label: 'رسیدِ خواندن', kind: 'toggle', defaultValue: true, advanced: true },
    ],
    requiredEnvs: ['CHAT_PROVIDER', 'CHAT_WS_URL'],
    dependentFeatures: ['چتِ مسابقه', 'اعلانِ تورنومنت', 'پیامِ مستقیم', 'مانیتورینگِ چت'],
  },
  {
    id: 'storage',
    label: 'آپلودِ مدارک / فضای ذخیره',
    description: 'اسکرین‌شاتِ نتیجه، مدارکِ اختلاف، مدارکِ KYC، کاور و آواتار.',
    providers: sel('local_mock', 's3', 'cloudflare_r2', 'supabase_storage', 'firebase_storage', 'custom_upload_api'),
    mockProvider: 'local_mock',
    fields: [
      { key: 'bucket', label: 'Bucket', kind: 'text', required: true },
      { key: 'region', label: 'Region', kind: 'text' },
      { key: 'accessKey', label: 'Access Key', kind: 'password', secret: true, required: true },
      { key: 'secretKey', label: 'Secret Key', kind: 'password', secret: true, required: true },
      { key: 'publicBaseUrl', label: 'Public Base URL', kind: 'text' },
      { key: 'signedUrlExpiry', label: 'انقضای Signed URL (دقیقه)', kind: 'number', defaultValue: 15, advanced: true },
      { key: 'maxFileSizeMb', label: 'حداکثرِ حجمِ فایل (MB)', kind: 'number', defaultValue: 10, required: true, advanced: true },
      { key: 'virusScan', label: 'اسکنِ ویروس', kind: 'toggle', defaultValue: false, advanced: true },
      { key: 'compression', label: 'فشرده‌سازیِ تصویر', kind: 'toggle', defaultValue: true, advanced: true },
      { key: 'privateMode', label: 'حالتِ خصوصی', kind: 'toggle', defaultValue: true, advanced: true },
    ],
    requiredEnvs: ['STORAGE_PROVIDER', 'STORAGE_BUCKET', 'STORAGE_ACCESS_KEY', 'STORAGE_SECRET_KEY'],
    dependentFeatures: ['آپلودِ مدرکِ مسابقه', 'مدرکِ اختلاف', 'مدارکِ KYC', 'کاورِ بازی', 'آواتار', 'پیوستِ تیکت'],
  },
  {
    id: 'payment',
    label: 'درگاهِ پرداخت',
    description: 'شارژِ کیفِ پول، هزینه‌ی ورودی و بازپرداخت. واحدِ پول: تومان.',
    providers: sel('mock_gateway', 'zarinpal', 'idpay', 'payping', 'stripe', 'custom'),
    mockProvider: 'mock_gateway',
    fields: [
      { key: 'merchantId', label: 'Merchant ID', kind: 'text', required: true },
      { key: 'apiKey', label: 'API Key', kind: 'password', secret: true, required: true },
      { key: 'callbackUrl', label: 'Callback URL', kind: 'text', required: true },
      { key: 'webhookUrl', label: 'Webhook URL', kind: 'text' },
      { key: 'sandbox', label: 'حالتِ Sandbox', kind: 'toggle', defaultValue: true },
      { key: 'currency', label: 'واحدِ پول', kind: 'select', options: [{ value: 'toman', label: 'تومان' }], defaultValue: 'toman' },
      { key: 'minDeposit', label: 'حداقلِ واریز (تومان)', kind: 'number', defaultValue: 10000, advanced: true },
      { key: 'maxDeposit', label: 'حداکثرِ واریز (تومان)', kind: 'number', defaultValue: 50000000, advanced: true },
      { key: 'autoVerify', label: 'تأییدِ خودکارِ پرداخت', kind: 'toggle', defaultValue: true, advanced: true },
      { key: 'timeoutMinutes', label: 'مهلتِ پرداخت (دقیقه)', kind: 'number', defaultValue: 15, advanced: true },
    ],
    requiredEnvs: ['PAYMENT_PROVIDER', 'PAYMENT_MERCHANT_ID', 'PAYMENT_API_KEY', 'PAYMENT_CALLBACK_URL'],
    dependentFeatures: ['شارژِ کیفِ پول', 'هزینه‌ی ورودی', 'بازپرداخت', 'آماده‌سازیِ پرداخت'],
  },
  {
    id: 'wallet',
    label: 'کیفِ پول / Escrow / دفترِ کل',
    description: 'دفترِ کلِ دوطرفه، قفلِ escrow، آزادسازیِ جایزه و بازپرداخت.',
    providers: sel('mock_persistent', 'database', 'external_wallet_api'),
    mockProvider: 'mock_persistent',
    fields: [
      { key: 'escrowEnabled', label: 'فعال‌بودنِ Escrow', kind: 'toggle', defaultValue: true },
      { key: 'requireEscrowPaid', label: 'الزامِ Escrow برای تورنومنتِ پولی', kind: 'toggle', defaultValue: true },
      { key: 'financeApproval', label: 'الزامِ تأییدِ مالی برای پرداخت', kind: 'toggle', defaultValue: true },
      { key: 'autoRefundCancelled', label: 'بازپرداختِ خودکارِ تورنومنتِ لغوشده', kind: 'toggle', defaultValue: true, advanced: true },
      { key: 'payoutHoldHours', label: 'دوره‌ی نگه‌داریِ پرداخت (ساعت)', kind: 'number', defaultValue: 24, advanced: true },
      { key: 'disputePayoutLock', label: 'قفلِ پرداخت تا حلِ اختلاف', kind: 'toggle', defaultValue: true },
      { key: 'minWithdrawal', label: 'حداقلِ برداشت (تومان)', kind: 'number', defaultValue: 100000, advanced: true },
      { key: 'doubleEntry', label: 'دفترِ کلِ دوطرفه', kind: 'toggle', defaultValue: true },
    ],
    requiredEnvs: [],
    dependentFeatures: ['قفلِ escrow', 'آزادسازیِ جایزه', 'بازپرداخت', 'برداشت', 'تعدیلِ دستی'],
  },
  {
    id: 'kyc',
    label: 'احرازِ هویت (KYC)',
    description: 'احرازِ هویت برای برداشتِ جایزه و تورنومنتِ پولی.',
    providers: sel('internal_manual_review', 'mock_kyc', 'custom_kyc_api', 'sumsub', 'stripe_identity'),
    mockProvider: 'mock_kyc',
    fields: [
      { key: 'requireForPayout', label: 'الزامِ KYC برای پرداختِ جایزه', kind: 'toggle', defaultValue: true },
      { key: 'requireForPaid', label: 'الزامِ KYC برای تورنومنتِ پولی', kind: 'toggle', defaultValue: false },
      { key: 'manualReview', label: 'بازبینیِ دستی', kind: 'toggle', defaultValue: true },
      { key: 'autoApproveDev', label: 'تأییدِ خودکار در توسعه', kind: 'toggle', defaultValue: true, advanced: true },
      { key: 'expiryDays', label: 'انقضا (روز)', kind: 'number', defaultValue: 365, advanced: true },
      { key: 'apiKey', label: 'API Key', kind: 'password', secret: true },
      { key: 'webhookSecret', label: 'Webhook Secret', kind: 'password', secret: true, advanced: true },
    ],
    requiredEnvs: ['KYC_PROVIDER', 'KYC_API_KEY'],
    dependentFeatures: ['برداشتِ جایزه', 'تأییدِ پرداخت', 'تأییدِ برگزارکننده', 'بررسیِ کاربرِ مشکوک'],
  },
  {
    id: 'jobs',
    label: 'کارهای پس‌زمینه / زمان‌بند',
    description: 'بدونِ این، سناریوهای «مهلتِ گذشته»، «عدمِ حضورِ خودکار» و «هشدارِ خودکار» production-ready نیستند.',
    providers: sel('internal_mock', 'cron', 'bullmq', 'inngest', 'temporal', 'supabase_cron'),
    mockProvider: 'internal_mock',
    fields: [
      { key: 'secret', label: 'Job Secret', kind: 'password', secret: true },
      { key: 'concurrency', label: 'هم‌زمانی', kind: 'number', defaultValue: 4, advanced: true },
      { key: 'defaultTimeout', label: 'مهلتِ پیش‌فرض (ثانیه)', kind: 'number', defaultValue: 60, advanced: true },
    ],
    requiredEnvs: ['JOB_PROVIDER', 'JOB_SECRET'],
    dependentFeatures: ['بررسیِ مهلتِ مسابقه', 'عدمِ حضورِ خودکار', 'یادآوریِ خودکار', 'اعلانِ زمان‌بندی‌شده'],
    toggleListTitle: 'کارهای فعال',
    toggleList: [
      { key: 'check_registration_deadlines', label: 'بررسیِ مهلتِ ثبت‌نام' },
      { key: 'check_checkin_deadlines', label: 'بررسیِ مهلتِ چک‌این' },
      { key: 'send_checkin_reminders', label: 'یادآوریِ چک‌این' },
      { key: 'check_match_deadlines', label: 'بررسیِ مهلتِ مسابقه' },
      { key: 'send_missing_result_warnings', label: 'هشدارِ نتیجه‌ی ثبت‌نشده' },
      { key: 'mark_match_admin_review', label: 'انتقال به بازبینیِ مدیر' },
      { key: 'auto_no_show_after_timeout', label: 'عدمِ حضورِ خودکار پس از مهلت' },
      { key: 'auto_confirm_uncontested_result', label: 'تأییدِ خودکارِ نتیجه‌ی بی‌اعتراض' },
      { key: 'close_expired_disputes', label: 'بستنِ اختلافِ منقضی' },
      { key: 'release_scheduled_announcements', label: 'اعلانِ زمان‌بندی‌شده' },
      { key: 'payout_eligibility_check', label: 'بررسیِ واجدِشرایطیِ پرداخت' },
      { key: 'cleanup_temp_uploads', label: 'پاکسازیِ فایل‌های موقت' },
      { key: 'notification_retry_worker', label: 'workerِ تلاشِ مجددِ اعلان' },
    ],
  },
  {
    id: 'webhooks',
    label: 'Webhookها',
    description: 'دریافتِ callback از پرداخت، KYC، storage و تحویلِ اعلان.',
    providers: sel('internal', 'custom'),
    mockProvider: 'internal',
    fields: [
      { key: 'baseUrl', label: 'Public Webhook Base URL', kind: 'text', placeholder: 'https://api.shelter.gg/webhooks', required: true },
      { key: 'signingSecret', label: 'Signing Secret', kind: 'password', secret: true, required: true },
      { key: 'retentionDays', label: 'نگه‌داریِ لاگِ رویداد (روز)', kind: 'number', defaultValue: 30, advanced: true },
      { key: 'ipAllowlist', label: 'IP Allowlist', kind: 'textarea', advanced: true },
      { key: 'verifySignature', label: 'الزامِ تأییدِ امضا', kind: 'toggle', defaultValue: true },
      { key: 'idempotency', label: 'الزامِ Idempotency Key', kind: 'toggle', defaultValue: true, advanced: true },
    ],
    requiredEnvs: ['WEBHOOK_SIGNING_SECRET'],
    dependentFeatures: ['callbackِ پرداخت', 'callbackِ KYC', 'تحویلِ اعلان', 'رویدادِ storage'],
  },
  {
    id: 'moderation',
    label: 'نظارت / ضدِتقلب',
    description: 'گزارش، چتِ سمی، مدرکِ جعلی و حسابِ مشکوک.',
    providers: sel('internal_rules', 'custom_api', 'perspective_api', 'mod_ai'),
    mockProvider: 'internal_rules',
    fields: [
      { key: 'profanityFilter', label: 'فیلترِ ناسزا', kind: 'toggle', defaultValue: true },
      { key: 'toxicThreshold', label: 'آستانه‌ی پیامِ سمی', kind: 'number', defaultValue: 3, advanced: true },
      { key: 'duplicateAccount', label: 'تشخیصِ حسابِ تکراری', kind: 'toggle', defaultValue: true },
      { key: 'noShowThreshold', label: 'آستانه‌ی عدمِ حضورِ مشکوک', kind: 'number', defaultValue: 2 },
      { key: 'autoMuteThreshold', label: 'آستانه‌ی mute خودکار', kind: 'number', defaultValue: 3, advanced: true },
      { key: 'autoReport', label: 'ساختِ خودکارِ گزارش', kind: 'toggle', defaultValue: true, advanced: true },
      { key: 'apiKey', label: 'API Key', kind: 'password', secret: true, advanced: true },
    ],
    requiredEnvs: [],
    dependentFeatures: ['گزارشِ تخلف', 'فیلترِ چت', 'تشخیصِ تقلب', 'پرچمِ مشکوک'],
  },
  {
    id: 'analytics',
    label: 'تحلیل / مانیتورینگ',
    description: 'مانیتورینگِ پروداکشن، خطاها و رویدادها.',
    providers: sel('internal_logs', 'sentry', 'posthog', 'google_analytics', 'datadog'),
    mockProvider: 'internal_logs',
    fields: [
      { key: 'sentryDsn', label: 'Sentry DSN', kind: 'password', secret: true },
      { key: 'posthogKey', label: 'PostHog Key', kind: 'password', secret: true },
      { key: 'sampleRate', label: 'نرخِ نمونه‌برداری', kind: 'number', defaultValue: 1, advanced: true },
      { key: 'captureFrontend', label: 'ثبتِ خطاهای فرانت', kind: 'toggle', defaultValue: true, advanced: true },
      { key: 'captureBackend', label: 'ثبتِ خطاهای بک‌اند', kind: 'toggle', defaultValue: true, advanced: true },
      { key: 'captureAdminActions', label: 'ثبتِ اقدام‌های مدیر', kind: 'toggle', defaultValue: true, advanced: true },
      { key: 'piiMasking', label: 'ماسکِ PII', kind: 'toggle', defaultValue: true, advanced: true },
    ],
    requiredEnvs: ['SENTRY_DSN', 'POSTHOG_KEY'],
    dependentFeatures: ['مانیتورینگِ خطا', 'ردیابیِ رویداد', 'ثبتِ اقدامِ مدیر'],
  },
];

export const INTEGRATION_BY_ID = Object.fromEntries(INTEGRATIONS.map((i) => [i.id, i])) as Record<IntegrationProviderType, IntegrationDef>;

export const FEATURE_FLAGS: FeatureFlagDef[] = [
  { key: 'enable_realtime_chat', label: 'چتِ بلادرنگ', description: 'چتِ مسابقه و پیامِ مستقیم', dependsOn: ['chat'] },
  { key: 'enable_payment_gateway', label: 'درگاهِ پرداخت', description: 'شارژ و پرداختِ ورودی', dependsOn: ['payment'] },
  { key: 'enable_kyc', label: 'احرازِ هویت', description: 'KYC برای برداشت', dependsOn: ['kyc'] },
  { key: 'enable_evidence_upload', label: 'آپلودِ مدرک', description: 'اسکرین‌شات و مدارک', dependsOn: ['storage'] },
  { key: 'enable_background_jobs', label: 'کارهای پس‌زمینه', description: 'مهلت‌ها و خودکارها', dependsOn: ['jobs'] },
  { key: 'enable_sms_otp', label: 'پیامک / OTP', description: 'تأییدِ شماره و 2FA', dependsOn: ['sms'] },
  { key: 'enable_push_notifications', label: 'اعلانِ Push', description: 'اعلانِ فوری', dependsOn: ['notification'] },
  { key: 'enable_auto_no_show', label: 'عدمِ حضورِ خودکار', description: 'no-show پس از مهلت', dependsOn: ['jobs', 'notification'] },
  { key: 'enable_auto_result_confirmation', label: 'تأییدِ خودکارِ نتیجه', description: 'تأییدِ بی‌اعتراض', dependsOn: ['jobs'] },
  { key: 'enable_public_organizer_requests', label: 'درخواستِ عمومیِ برگزارکننده', description: 'برنامه‌ی برگزارکننده‌ها' },
  { key: 'enable_ladders', label: 'نردبان‌ها', description: 'رتبه‌بندیِ ELO' },
  { key: 'enable_communities', label: 'کامیونیتی‌ها', description: 'فضاهای جامعه' },
  { key: 'enable_payouts', label: 'پرداختِ جوایز', description: 'آزادسازیِ جایزه', dependsOn: ['wallet', 'payment', 'kyc'] },
];

export const ENV_VARS: EnvVarDef[] = [
  { name: 'NOTIFICATION_PROVIDER', description: 'ارائه‌دهنده‌ی اعلان', requiredInProduction: true, example: 'one_signal', type: 'notification' },
  { name: 'NOTIFICATION_API_KEY', description: 'کلیدِ سرویسِ اعلان', requiredInProduction: true, example: 'os_live_xxx', type: 'notification', secret: true },
  { name: 'EMAIL_PROVIDER', description: 'ارائه‌دهنده‌ی ایمیل', requiredInProduction: true, example: 'resend', type: 'email' },
  { name: 'EMAIL_FROM', description: 'ایمیلِ فرستنده', requiredInProduction: true, example: 'no-reply@shelter.gg', type: 'email' },
  { name: 'SMTP_HOST', description: 'هاستِ SMTP', requiredInProduction: false, example: 'smtp.resend.com', type: 'email' },
  { name: 'SMTP_PORT', description: 'پورتِ SMTP', requiredInProduction: false, example: '587', type: 'email' },
  { name: 'SMTP_USER', description: 'کاربرِ SMTP', requiredInProduction: false, example: 'apikey', type: 'email' },
  { name: 'SMTP_PASSWORD', description: 'رمزِ SMTP', requiredInProduction: false, example: '••••', type: 'email', secret: true },
  { name: 'SMS_PROVIDER', description: 'ارائه‌دهنده‌ی پیامک', requiredInProduction: false, example: 'kavenegar', type: 'sms' },
  { name: 'SMS_API_KEY', description: 'کلیدِ پیامک', requiredInProduction: false, example: 'kv_xxx', type: 'sms', secret: true },
  { name: 'CHAT_PROVIDER', description: 'ارائه‌دهنده‌ی چت', requiredInProduction: false, example: 'pusher', type: 'chat' },
  { name: 'CHAT_WS_URL', description: 'آدرسِ WebSocket', requiredInProduction: false, example: 'wss://chat.shelter.gg', type: 'chat' },
  { name: 'STORAGE_PROVIDER', description: 'ارائه‌دهنده‌ی ذخیره', requiredInProduction: true, example: 'cloudflare_r2', type: 'storage' },
  { name: 'STORAGE_BUCKET', description: 'نامِ Bucket', requiredInProduction: true, example: 'shelter-prod', type: 'storage' },
  { name: 'STORAGE_ACCESS_KEY', description: 'Access Key', requiredInProduction: true, example: 'AKIA...', type: 'storage', secret: true },
  { name: 'STORAGE_SECRET_KEY', description: 'Secret Key', requiredInProduction: true, example: '••••', type: 'storage', secret: true },
  { name: 'PAYMENT_PROVIDER', description: 'درگاهِ پرداخت', requiredInProduction: true, example: 'zarinpal', type: 'payment' },
  { name: 'PAYMENT_MERCHANT_ID', description: 'شناسه‌ی پذیرنده', requiredInProduction: true, example: 'xxxxxxxx-xxxx', type: 'payment' },
  { name: 'PAYMENT_API_KEY', description: 'کلیدِ درگاه', requiredInProduction: true, example: '••••', type: 'payment', secret: true },
  { name: 'PAYMENT_CALLBACK_URL', description: 'آدرسِ بازگشت', requiredInProduction: true, example: 'https://shelter.gg/pay/callback', type: 'payment' },
  { name: 'KYC_PROVIDER', description: 'ارائه‌دهنده‌ی KYC', requiredInProduction: false, example: 'sumsub', type: 'kyc' },
  { name: 'KYC_API_KEY', description: 'کلیدِ KYC', requiredInProduction: false, example: '••••', type: 'kyc', secret: true },
  { name: 'JOB_PROVIDER', description: 'زمان‌بندِ کارها', requiredInProduction: true, example: 'bullmq', type: 'jobs' },
  { name: 'JOB_SECRET', description: 'کلیدِ کارها', requiredInProduction: true, example: '••••', type: 'jobs', secret: true },
  { name: 'WEBHOOK_SIGNING_SECRET', description: 'کلیدِ امضای webhook', requiredInProduction: true, example: 'whsec_xxx', type: 'webhooks', secret: true },
  { name: 'SENTRY_DSN', description: 'DSN سنتری', requiredInProduction: false, example: 'https://...@sentry.io/..', type: 'analytics', secret: true },
  { name: 'POSTHOG_KEY', description: 'کلیدِ PostHog', requiredInProduction: false, example: 'phc_xxx', type: 'analytics', secret: true },
];

/** وابستگیِ سناریوی FC26 128-player به سرویس‌ها. */
export const FC26_DEPENDENCIES: { feature: string; types: IntegrationProviderType[] }[] = [
  { feature: 'هشدارِ نتیجه‌ی ثبت‌نشده', types: ['notification', 'jobs'] },
  { feature: 'عدمِ حضورِ خودکار', types: ['jobs', 'notification'] },
  { feature: 'چتِ مسابقه', types: ['chat'] },
  { feature: 'آپلودِ مدرک', types: ['storage'] },
  { feature: 'مدرکِ اختلاف', types: ['storage', 'moderation'] },
  { feature: 'پرداختِ جایزه', types: ['wallet', 'payment', 'kyc'] },
  { feature: 'ردیابیِ اقدامِ مدیر', types: ['analytics'] },
];
